---
title: "DA_Grpproject"
author: "Smriti"
date: "`r Sys.Date()`"
output: html_document
---

knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/hp/Desktop/DA grp project")
library(tidyverse)
library(stargazer)
library(gt)
library(dplyr)
educ <- read.csv("sect2_education.csv", na.strings = " ")
health<-read.csv("sect3_health.csv", na.strings = " ")
income<-read.csv("sect13_income.csv", na.strings = " ")
remittances<-read.csv("sect5_remittances.csv", na.strings = " ")
food<-read.csv("sect6c_aggregate_food_1.csv", na.strings = " ")




Merging datasets


#filtering required columns from all datasets
neduc <- data.frame(educ$hhid,educ$zone, educ$state, educ$lga, educ$sector, educ$ea, educ$indiv, educ$s02q08)
nhealth<-data.frame(health$hhid,health$zone,health$state, health$lga,health$sector, health$ea, health$indiv, health$s03q24)
nincome<-data.frame(income$hhid, income$zone_id, income$state_id, income$lga, income$sector, income$ea_code, income$source_cd, income$s13q02)
nremittances<-data.frame(remittances$hhid, remittances$zone, remittances$state, remittances$lga, remittances$sector, remittances$indiv, remittances$ea, remittances$s05q02b,remittances$s05q02a)
nfood<-data.frame(food$hhid,food$state, food$sector, food$zone, food$lga, food$ea,
food$s06cq08)

neduc <- neduc %>% rename(hhid = educ.hhid)
nhealth <- nhealth %>% rename(hhid = health.hhid)
nincome <- nincome %>% rename(hhid = income.hhid)
nremittances <- nremittances %>% rename(hhid = remittances.hhid)
nfood <- nfood %>% rename(hhid = food.hhid)

#merging all data sets
merged_data <- inner_join(neduc, nhealth, by = 'hhid')%>% 
               inner_join(nincome, by = 'hhid') %>% 
               inner_join(nremittances, by = 'hhid') %>% 
               inner_join(nfood, by = 'hhid')

